### ISSUE TITLE
Adding Levoit Core 200s

### ISSUE THREAD

**Issue by richtiger** [acvigue/esphome-levoit-air-purifier#11]
Has anyone done anything with the 200s lately?

I was able to get the 200s working by duplicating what was added for the 400 with a couple differences. However, I can’t seem to figure out the nightlight. 

I put factory firmware back on, connected it to the app and issued commands from the app while my logic analyzer is connected, but not getting anything. Connecting both tx and rx to its own channel (using Logic, set as async serial with baud at 115200) and should see some, right?

**Comment by rwtallant13** [comment]
Would you mind sharing your yaml config? I just did this to my 200s with the default 300s config and would like to have some more control. Thanks.

**Comment by richtiger** [comment]
I've been using the updates from https://github.com/acvigue/esphome-levoit-air-purifier/pull/13 and everything has been working with a 200s.

**Comment by acvigue** [comment]
#13 has been merged.
